# example-node1-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-sno
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "example-sno"
  namespace: "example-sno"
spec:
  baseDomain: "example2.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.16.9-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFcGadvq//BwdEyE6BaDmuNKOJwSq4q9Mlyf/stLkEev kni@bastion.pele"
  clusters:
  - clusterName: "example-sno"
    networkType: "OVNKubernetes"
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-sno-ranGen.yaml will apply to all clusters with 'group-du-sno: ""'
      group-du-sno: ""
      # ../policygentemplates/example-sno-site.yaml will apply to all clusters with 'sites: "example-sno"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "example-sno"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.63.0/24
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #- 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    nodes:
      - hostName: "example-sno"
        role: "master"
        # Optionally; This can be used to configure desired BIOS setting on a host:
        #biosConfigRef:
        #  filePath: "example-hw.profile"
        bmcAddress: "redfish-virtualmedia+http://192.168.62.200:8000/redfish/v1/Systems/50cc6827-1a04-4957-a81d-9b9e90bb1f18"
        bmcCredentialsName:
          name: "bmh-secret"
        bootMACAddress: "52:54:00:b4:44:44"
        # Use UEFISecureBoot to enable secure boot
        bootMode: "UEFI"
          #        rootDeviceHints:
          #          wwn: "0x11111000000asd123"
        # example of diskPartition below is used for image registry (check ImageRegistry.md for more details), but it's not limited to this use case
#        diskPartition:
#          - device: /dev/disk/by-id/wwn-0x11111000000asd123 # match rootDeviceHints
#            partitions:
#              - mount_point: /var/imageregistry
#                size: 102500
#                start: 344844
#        cpuset: "0-1,52-53"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "52:54:00:b4:44:44"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.63.51
                    prefix-length: 24
                ipv6:
                  enabled: false
                    #                  address:
                  # For SNO sites with static IP addresses, the node-specific,
                  # API and Ingress IPs should all be the same and configured on
                  # the interface
                  #                  - ip: 192.168.63.188
                  #                    prefix-length: 24
            dns-resolver:
              config:
                server:
                - 192.168.63.20
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: enp1s0
                next-hop-address: 192.168.63.1
                table-id: 254
