# example-node[123]-bmh-secret & assisted-deployment-pull-secret need to be created under same namespace example-3node
---
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "3node"
  namespace: "3node"
spec:
  baseDomain: "example.com"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.16.9-x86-64-appsub"
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHQ67UjA6/++XL0FNBJ2JuUw9Y8TXSDY9K098sf17iZx root@prov9.local"
  clusters:
  - clusterName: "3node"
    networkType: "OVNKubernetes"
    # It is strongly recommended to include crun manifests as part of the additional install-time manifests for 4.13+.
    # The crun manifests can be obtained from source-crs/optional-extra-manifest/ and added to the git repo ie.3node-extra-manifest.
    # extraManifestPath: 3node-extra-manifest
    clusterLabels:
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples
     # du-profile: "latest"
      # These example cluster labels correspond to the bindingRules in the PolicyGenTemplate examples in ../policygentemplates:
      # ../policygentemplates/common-ranGen.yaml will apply to all clusters with 'common: true'
      common: true
      # ../policygentemplates/group-du-3node-ranGen.yaml will apply to all clusters with 'group-du-3node: ""'
      group-du-3node: ""
      # ../policygentemplates/example-multinode-site.yaml will apply to all clusters with 'sites: "example-multinode"'
      # Normally this should match or contain the cluster name so it only applies to a single cluster
      sites : "3node"
    clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
    machineNetwork:
      - cidr: 192.168.63.0/24
    serviceNetwork:
      - 172.30.0.0/16
    #additionalNTPSources:
    #- 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    #clusterNetwork:
     # - cidr: 1001:1::/48
      #  hostPrefix: 64
    # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
    #apiVIP: 1111:2222:3333:4444::1:1
    #ingressVIP: 1111:2222:3333:4444::1:2
    #serviceNetwork:
     # - 1001:2::/112
    #additionalNTPSources:
    #  - 1111:2222:3333:4444::2
    # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
    #crTemplates:
    #  KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
    # Optionally; This can be used to to configure desired BIOS setting on all nodes in this cluster:
    #biosConfigRef:
    #  filePath: "example-hw.profile"
    nodes:
      - hostName: "node1.3node.example.com"
        role: "master"
        nodeLabels:
          node-role.kubernetes.io/master-du:
          custom-label/parameter1: true
        bmcAddress: "redfish-virtualmedia+http://192.168.62.250:8000/redfish/v1/Systems/ecefa8ee-fbc5-4728-9abc-ab10503e3bbf"
        bmcCredentialsName:
          name: "bmh1-secret"
        bootMACAddress: "52:54:00:a4:db:55"
        # Use UEFISecureBoot to enable secure boot for this node
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/vda"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "52:54:00:a4:db:55"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                ipv6:
                  enabled: false
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.63.77
                    prefix-length: 24
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 192.168.63.20
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: enp1s0
                next-hop-address: 192.168.63.1
                table-id: 254
      - hostName: "node2.3node.example.com"
        role: "master"
        bmcAddress: "redfish-virtualmedia+http://192.168.62.250:8000/redfish/v1/Systems/95c8eb0d-7a05-4cbe-ac29-1d3bb466f728"
        bmcCredentialsName:
          name: "bmh2-secret"
        bootMACAddress: "52:54:00:a4:db:65"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName: "/dev/vda"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "52:54:00:a4:db:65"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                ipv6:
                  enabled: false
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.63.78
                    prefix-length: 24
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 192.168.63.20
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: enp1s0
                next-hop-address: 192.168.63.1
                table-id: 254
      - hostName: "node3.3node.example.com"
        role: "master"
        bmcAddress: "redfish-virtualmedia+http://192.168.62.250:8000/redfish/v1/Systems/1b19d193-1cf2-4025-aaec-33fcaa8bfe6b"
        bmcCredentialsName:
          name: "bmh3-secret"
        bootMACAddress: "52:54:00:a4:db:75"
        bootMode: "UEFI"
        rootDeviceHints:
          deviceName:  "/dev/vda"
        nodeNetwork:
          interfaces:
            - name: enp1s0
              macAddress: "52:54:00:a4:db:75"
          config:
            interfaces:
              - name: enp1s0
                type: ethernet
                state: up
                ipv6:
                  enabled: false
                ipv4:
                  enabled: true
                  address:
                  - ip: 192.168.63.79
                    prefix-length: 24
            dns-resolver:
              config:
                search:
                - example.com
                server:
                - 192.168.63.20
            routes:
              config:
              - destination: 0.0.0.0/0
                next-hop-interface: enp1s0
                next-hop-address: 192.168.63.1
                table-id: 254
